export const traductions: {[key: string]: {[key: string]: {[key: string]: string}}} = {
    en: {
        app:{
            title: 'SQLdle',
            description: 'Build the correct SQL query to solve the challenge and test your database skills!',
        },
        game: {
            'challenge': 'Challenge',
            'howto': 'How to Play',
            'title': 'Database Challenge',
            'task': 'Your Task:',
            'schema': 'Database Schema:',
            'query': 'Your SQL Query:',
            'words': 'Available Words:',
            'attempts': 'Attempts:',
            'check': 'Check Query',
            'stats': 'Stats',
            'drag': 'Drag words here to build your query...',
            'next': 'Next Challenge',
            'won': 'Challenge completed!',
            'taken_attempts': 'Correct! You solved it in %s attempts.',
        },
        stats: {
            'title': 'Statistics',
            'completed': 'Challenges Completed',
            'average': 'Avg. Attempts per Challenge',
            'current': 'Current Streak',
            'best': 'Best Streak',
            'total': 'Total Attempts:',
            'rate': 'Success Rate:',
            'performance': 'Performance',
        }
    },
    es: {
        app: {
            title: 'SQLdle',
            description: '¡Construye la consulta SQL correcta para resolver el desafío!',
        },
        game: {
            'challenge': 'Desafío',
            'howto': 'Cómo Jugar',
            'title': 'Desafío de Base de Datos',
            'task': 'Tu tarea:',
            'schema': 'Esquema de la Base de Datos:',
            'query': 'Tu Consulta SQL:',
            'words': 'Palabras Disponibles:',
            'attempts': 'Intentos:',
            'check': 'Comprobar Consulta',
            'stats': 'Estadísticas',
            'drag': 'Arrastra las palabras aquí para construir tu consulta...',
            'next': 'Siguiente Desafío',
            'won': '¡Desafío completado!',
            'taken_attempts': '¡Correcto! Lo resolviste en %s intentos.',
        },
        stats: {
            'title': 'Estadísticas',
            'completed': 'Desafíos Completados',
            'average': 'Intentos Promedio por Desafío',
            'current': 'Racha Actual',
            'best': 'Mejor Racha',
            'total': 'Intentos Totales:',
            'rate': 'Tasa de Éxito:',
            'performance': 'Rendimiento',
        }
    },
    eu: {
        app: {
            title: 'SQLdle',
            description: 'Eraiki zuzeneko SQL kontsulta erronka konpontzeko!',
        },
        game: {
            'challenge': 'Erronka',
            'howto': 'Nola Jolastu',
            'title': 'Datubase Erronka',
            'task': 'Zure lanerako:',
            'schema': 'Datubase Eskema:',
            'query': 'Zure SQL Kontsulta:',
            'words': 'Hitz erabilgarriak:',
            'attempts': 'Saiakera:',
            'check': 'Kontsulta Egiaztatu',
            'stats': 'Estatistikak',
            'drag': 'Hitzak arrastatu hemen zure kontsulta eraikitzeko...',
            'next': 'Hurrengo Erronka',
            'won': 'Erronka gainditua!',
            'taken_attempts': 'Zuzena! %s saiakeratan ebaztu duzu.',
        },
        stats: {
            'title': 'Estatistikak',
            'completed': 'Erronka Gaineratuak',
            'average': 'Batazbesteko Saiakerak',
            'current': 'Uneko Sorta',
            'best': 'Hobereneko Sorta',
            'total': 'Saiakerak Guztira:',
            'rate': 'Arrakasta Tasa:',
            'performance': 'Eginkiz',
        }
    },
    sv: {
        app: {
            title: 'SQLdle',
            description: 'Bygg den korrekta SQL-frågan för att lösa utmaningen!',
        },
        game: {
            'challenge': 'Utmaning',
            'howto': 'Hur asdadasd', 
            'title': 'Databasutmaning',
            'task': 'Din uppgift:',
            'schema': 'Databasschema:',
            'query': 'Din SQL-fråga:',
            'words': 'Tillgängliga ord:',
            'attempts': 'Försök:',
            'check': 'Kontrollera fråga',
            'stats': 'Statistik',
            'drag': 'Dra ord hit för att bygga din fråga...',
            'next': 'Nästa utmaning',
            'won': 'Utmaning slutförd!',
            'taken_attempts': 'Korrekt! Du löste det på %s försök.',
        },
        stats: {
            'title': 'Statistik',
            'completed': 'Slutförda utmaningar',
            'average': 'Genomsnittligt antal försök per utmaning',
            'current': 'Nuvarande svit',
            'best': 'Bästa svit',
            'total': 'Totalt antal försök:',
            'rate': 'Framgångsgrad:',
            'performance': 'Prestanda',
        }
    },
}